import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import SideNav from "@/components/ui/dashboard/sidenav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          {/* Sidebar */}
          
          <SideNav />
         

          {/* Conteúdo principal */}
          <div className="flex flex-col w-full">
            <Header />
            <main className="flex-grow ml-16 p-6 md:overflow-y-auto md:p-12">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}

